nlmixr2/nlmixr2est

DESCRIPTION, README.Rmd, README.md, _pkgdown.yml, build/install.R, build/test_install.R, build/update.R, vignettes/running_nlmixr.Rmd, vignettes/xgxr-nlmixr-ggpmx.Rmd
=> Update nlmixrdevelopment -> nlmixr2 and similar changes

build/test_install.R
=> remove snakecharmr and (most) python references

README.Rmd, README.md
Fix #23 while not repeating ourselves
=> Updated installation instructions

tests/testthat/test-broom.R, tests/testthat/test-cov-focei.R, tests/testthat/test-issue-169.R, tests/testthat/test-issue-429.R, tests/testthat/test-issue-502.R, tests/testthat/test-multiple-endpoint.R, tests/testthat/test-piping.R, tests/testthat/test-saem-aic.R, tests/testthat/test-saem-theo_sd.R, tests/testthat/test-table-cmt.R, tests/testthat/test-ui-good-models.R, tests/testthat/test-ui-pred-err.R
This makes some of the tests that have obvious fixes word better, and it improves testthat edition 3 compatibilty.
=> Simple testing fixes and better compatibility with testthat edition 3

R/focei.R, src/inner.cpp, tests/testthat/test-sens-fd.R
=> Make sure all the models are loaded; adjust sens-fd

man-roxygen/uif.R, man/foceiControl.Rd, man/nlmixr2.Rd, man/nlmixr2Sim.Rd
While rebuilding the docs, there was a missing brace that I fixed.  (FYI, the emacs command `check-parens` is awesome!  https://stackoverflow.com/questions/4319712/how-can-i-find-missing-or-mismatched-braces-parens-in-emacs)
=> Rebuild docs; fix missing brace issue in uif.R (and some reformatting trying to find the missing brace)

NEWS.md, man/saemControl.Rd
Rebuilt docs without any code changes
=> doc update (no code changes)

R/saemRxUiGetModel.R, tests/testthat/test-unary-mu.R
=> Test (that fails) for unary mu

R/nlmixr2Est.R
=> Clearer message for things like `rxSolve` that has its own methods

DESCRIPTION, R/nlme.R, R/saem.R, R/saemControl.R, R/saemRxUiGet.R, R/saemRxUiGetModel.R, man/saemControl.Rd, tests/testthat/test-fix-cov.R
=> Fixed parameters are now non-mu referenced by mu-ref

src/inner.cpp
=> Remove unused code (and some commenting and whitespace changes)

NEWS.md, R/print.R, R/resid.R, src/Makevars.in, src/censEst.cpp, src/censEst.h, src/censResid.cpp, src/cwres.cpp, src/inner.cpp, src/npde.cpp, tests/testthat/test-focei-cens.R
=> 179 m4 method simulations may be off

DESCRIPTION, R/nmObjGet.R, src/armahead.h, src/inner.cpp, src/nearPD.cpp, src/saem.cpp, src/shi21.cpp
=> 200 rcpparmadillo 2

.github/workflows/R-CMD-check.yaml
This updates the CI workflow to the current versions which are recommended by r-lib/actions.  As many things have changed, it may need tweaks to work correctly.
=> Update CI workflow to current versions

NEWS.md, src/inner.cpp, tests/testthat/test-focei-inner.R
=> 318 fix bound

man/nlmixr2NlmeControl.Rd, man/nlmixrAddObjectiveFunctionDataFrame.Rd
=> Rebuild documentation

NEWS.md, R/addCwres.R, tests/testthat/test-addCwres.R
=> Make addCwres() error clearer for model with no etas

R/cov.R, R/foceiControl.R, R/nlme.R, R/saemControl.R, man/foceiControl.Rd, man/nlmixr2NlmeControl.Rd, man/saemControl.Rd, man/setCov.Rd
=> Update documentation to link parts together (and some minor code formatting changes)

src/cwres.cpp, src/inner.cpp, src/nearPD.cpp, src/npde.cpp, src/saem.cpp, src/shi21.cpp
This removes most of the compiler warnings that are coming from within nlmixr2est.  It should have no effects on the functionality of the code.
=> Quieter compile

R/RcppExports.R, R/foceiControl.R, R/lbfgsb3c.R, R/model.R, R/n1qn1.R, R/nlmixr2output.R, R/nls.R, R/vpc.R, man/bobyqaControl.Rd, man/dot-foceiPreProcessData.Rd, man/dot-nlmixrNlsFun.Rd, man/foceiControl.Rd, man/lbfgsb3cControl.Rd, man/n1qn1Control.Rd, man/newuoaControl.Rd, man/nlmControl.Rd, man/nlminbControl.Rd, man/nlmixr2NlmeControl.Rd, man/nlsControl.Rd, man/optimControl.Rd, man/saemControl.Rd, man/uobyqaControl.Rd, man/vpcSim.Rd, src/RcppExports.cpp, src/nlm.cpp, src/rprintf.c, tests/testthat/test-focei-cens.R, tests/testthat/test-lag.R, tests/testthat/test-nonmu.R, tests/testthat/test-udf.R
=> 411 cran requests

NEWS.md, R/focei.R, R/foceiControl.R, R/n1qn1.R, R/nlm.R, R/nls.R, R/optim.R, R/saem.R, R/uobyqa.R, R/utils.R, man/nlmixr2AugPredSolve.Rd, man/nmNearPD.Rd
It is no longer there.  I will add it back.
_Originally posted by @mattfidler in https://github.com/nlmixr2/nlmixr2/discussions/252#discussioncomment-10256229_
=> It is no longer there.  I will add it back.

NEWS.md, R/addCwres.R, R/augPred.R, R/rxsolve.R
=> Read relevant `tableControl()` options from `nlmixr2` and override `control=rxControl()`

.github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml, .github/workflows/test-coverage.yaml, DESCRIPTION, NEWS.md, R/onLoad.R, src/init.c, src/inner.cpp
=> Remove abi linkage to lbfgsb3c

NEWS.md, R/mu2.R, R/saemRxUiGetModel.R, tests/testthat/test-saem-mu.R
Need to have mu referencing based on derived variables for example:
```r
if (cat == "a" || cat == "b") {
v <- "high"
} else {
v <- "low"
}
a = tA + eta.a + (v == "high") * v.high
```
=> `mu` referencing based on derived variables

NEWS.md, R/mu2.R, tests/testthat/test-saem-mu.R
=> mu-4 referencing

src/scale.h, tests/testthat/test-nls.R
Closes #485
Now scaling will fall back to unscaled if every parameter is zero.
Also adds some divide by zero protection for denominators
=> Scaling now falls back to unscaled

R/focei.R, tests/testthat/test-focei-eta-only.R
=> Fix eta-only model for focei

R/focei.R, R/nlm.R, R/nls.R, src/inner.cpp, src/scale.h, tests/testthat/test-resume-bobyqa.R
=> Fix for new linCmt()

NEWS.md, R/focei.R, R/foceiControl.R, R/hook.R, R/nlmixr2.R, R/nlmixr2global.R, man/foceiControl.Rd, tests/testthat/test-etaMat.R
=> Allow etaMat=fit for starting at etaMat for focei

R/RcppExports.R, R/focei.R, R/nlm.R, R/nls.R, R/preProcessLiteralFix.R, R/zzz.R, src/Makevars.in, src/RcppExports.cpp, src/init.c, src/rxcmp.cpp, tests/testthat/test-focei-eta-only.R, tests/testthat/test-saem-mu.R
=> Add some 3.0 compatibility layer

DESCRIPTION, NEWS.md, R/nlmixr2.R, tests/testthat/test-control-infer.R
=> Update for a null class check

R/resid.R, tests/testthat/test-ui-est-change.R
=> Remove and test that linCmt() are no longer in the fit

NEWS.md, R/augPred.R, R/simulate.R, R/vpc.R, tests/testthat/test-augpred.R
=> Apply pre-processing hooks for $simInfo and augPred(); test augPred

src/inner.cpp
=> Adjust ELS equation
